version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: wiki-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: wiki
      MYSQL_USER: wiki
      MYSQL_PASSWORD: wiki123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - wiki-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: wiki-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wiki-network

  # Wiki后端应用
  wiki-backend:
    build: .
    container_name: wiki-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wiki?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: wiki
      SPRING_DATASOURCE_PASSWORD: wiki123456
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    networks:
      - wiki-network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  wiki-network:
    driver: bridge
