apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-backend-staging
  namespace: wiki-staging
  labels:
    app: wiki-backend
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wiki-backend
      environment: staging
  template:
    metadata:
      labels:
        app: wiki-backend
        environment: staging
    spec:
      containers:
      - name: wiki-backend
        image: ghcr.io/xichen/wiki:develop
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "staging"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: wiki-db-secret
              key: url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: wiki-db-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wiki-db-secret
              key: password
        - name: SPRING_DATA_REDIS_HOST
          value: "redis-staging"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-backend-service-staging
  namespace: wiki-staging
  labels:
    app: wiki-backend
    environment: staging
spec:
  selector:
    app: wiki-backend
    environment: staging
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
